### ISSUE TITLE
Catch error when wikipedia can't find page for a particular query

### ISSUE THREAD

**Issue by jesmith0** [jesmith0/JeoPyrdy#13]
Application crashes when a search for a page that does not exist on Wikipedia is made.

Test game: 860

```
Traceback (most recent call last):
  File "main.py", line 174, in <module>
    if __name__ == "__main__": main()
  File "main.py", line 70, in main
    setup_ret = util.lib_setup()
  File "/Users/jeremy/Documents/git/JeoPyrdy/src/util.py", line 235, in lib_setup
    parsed_data = parse_jarchive()
  File "/Users/jeremy/Documents/git/JeoPyrdy/src/util.py", line 201, in parse_jarchive
    if res[i] == '404': res[i] = get_img_from_wiki(resp[i], i)
  File "/Users/jeremy/Documents/git/JeoPyrdy/src/util.py", line 70, in get_img_from_wiki
    page = wikipedia.page(query)
  File "/Users/jeremy/Library/Python/2.7/lib/python/site-packages/wikipedia/wikipedia.py", line 276, in page
    return WikipediaPage(title, redirect=redirect, preload=preload)
  File "/Users/jeremy/Library/Python/2.7/lib/python/site-packages/wikipedia/wikipedia.py", line 299, in __init__
    self.__load(redirect=redirect, preload=preload)
  File "/Users/jeremy/Library/Python/2.7/lib/python/site-packages/wikipedia/wikipedia.py", line 345, in __load
    raise PageError(self.title)
wikipedia.exceptions.PageError: Page id "bowlion" does not match any pages. Try another id!
```

**Comment by jesmith0** [comment]
https://github.com/jesmith0/jeopyrdy/commit/c878b2581be601152c1a9208ff33f3065dfe7de3
